// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetcore3_demo.Data;

namespace aspnetcore3_demo.Migrations
{
    [DbContext(typeof(RoutineDBContext))]
    [Migration("20200809162942_company_add_BankrupTime_property")]
    partial class company_add_BankrupTime_property
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("aspnetcore3_demo.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BankrupTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Industry")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Introduction")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Product")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Companys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19d42960-7635-4360-b25a-76f65793f352"),
                            Country = "USA",
                            Industry = "SoftWare",
                            Introduction = "Create Company",
                            Name = "Microsoft",
                            Product = "SoftWare"
                        },
                        new
                        {
                            Id = new Guid("0f5c57b3-1635-4666-9bb8-64171c0fc6ec"),
                            Country = "CN",
                            Industry = "SoftWare",
                            Introduction = "Tencent Company",
                            Name = "Tencent",
                            Product = "electrophile,game"
                        },
                        new
                        {
                            Id = new Guid("f72d336e-514d-41a1-a91e-f2eb0f4ddc46"),
                            Country = "CN",
                            Industry = "SoftWare",
                            Introduction = "WFT Company",
                            Name = "WFT",
                            Product = "web"
                        },
                        new
                        {
                            Id = new Guid("fb4d85e5-7b77-47f6-b223-e237706eb59a"),
                            Country = "CN",
                            Industry = "electrophile",
                            Introduction = "HQ Company",
                            Name = "HQ",
                            Product = "electrophile"
                        },
                        new
                        {
                            Id = new Guid("e85c5afe-389d-4eb1-9d8d-e8bd110a8092"),
                            Country = "TW",
                            Industry = "SoftWare",
                            Introduction = "Gaotong Company",
                            Name = "Gaotong",
                            Product = "USA"
                        },
                        new
                        {
                            Id = new Guid("dc9377f0-ef11-42a2-89df-69279fd7f81d"),
                            Country = "FR",
                            Industry = "electrophile",
                            Introduction = "Tongyong Company",
                            Name = "Tongyong",
                            Product = "USA"
                        },
                        new
                        {
                            Id = new Guid("2aa4335e-bfa1-4820-94f9-f7bb717a4997"),
                            Country = "USA",
                            Industry = "electrophile",
                            Introduction = "HP Company",
                            Name = "HP",
                            Product = "print"
                        },
                        new
                        {
                            Id = new Guid("201a3e4a-83bf-4e9c-ac82-8c45d6a57dfb"),
                            Country = "NL",
                            Industry = "SoftWare",
                            Introduction = "NOKIA Company",
                            Name = "NOKIA",
                            Product = "phone"
                        },
                        new
                        {
                            Id = new Guid("43a757aa-f01c-4f4c-ab6e-2f4a24647c9b"),
                            Country = "USA",
                            Industry = "SoftWare",
                            Introduction = "APPLIE Company",
                            Name = "APPLIE",
                            Product = "electrophile,software"
                        },
                        new
                        {
                            Id = new Guid("eb0744ea-d315-4f7f-8a3c-14ae4cf5e3e7"),
                            Country = "USA",
                            Industry = "SoftWare",
                            Introduction = "ORACLE Company",
                            Name = "ORACLE",
                            Product = "db"
                        },
                        new
                        {
                            Id = new Guid("939a8356-62ab-4701-8ca8-b34778c20a43"),
                            Country = "CN",
                            Industry = "web",
                            Introduction = "BAIDU Company",
                            Name = "BAIDU",
                            Product = "search enging"
                        },
                        new
                        {
                            Id = new Guid("45f8183b-2258-4589-b37c-a4d7939bf4df"),
                            Country = "CN",
                            Industry = "web",
                            Introduction = "BILIBILI Company",
                            Name = "BILIBILI",
                            Product = "web"
                        },
                        new
                        {
                            Id = new Guid("4b56e067-c5de-4846-948d-0917f79501d7"),
                            Country = "USA",
                            Industry = "web",
                            Introduction = "FACEBOOK Company",
                            Name = "FACEBOOK",
                            Product = "social contact"
                        },
                        new
                        {
                            Id = new Guid("7bfa2bc8-9748-4950-876e-9c733c4f5656"),
                            Country = "USA",
                            Industry = "web",
                            Introduction = "YOUTUBE Company",
                            Name = "YOUTUBE",
                            Product = "social contact"
                        },
                        new
                        {
                            Id = new Guid("947c05b7-b566-41b9-a466-e071f9c6c8e0"),
                            Country = "USA",
                            Industry = "software",
                            Introduction = "AMAZON Company",
                            Name = "AMAZON",
                            Product = "web"
                        },
                        new
                        {
                            Id = new Guid("74f4655e-7206-4e85-98ff-695841ecd8b2"),
                            Country = "USA",
                            Industry = "hardware",
                            Introduction = "DELL Company",
                            Name = "DELL",
                            Product = "computer"
                        },
                        new
                        {
                            Id = new Guid("5fece8c6-afae-407a-96b6-c97aca57e4c2"),
                            Country = "JP",
                            Industry = "hardware",
                            Introduction = "SONY Company",
                            Name = "SONY",
                            Product = "electrophile"
                        },
                        new
                        {
                            Id = new Guid("fee4429e-4ed0-4b4b-9ad0-829e6d7dd496"),
                            Country = "KP",
                            Industry = "hardware",
                            Introduction = "SAMSUN Company",
                            Name = "SAMSUN",
                            Product = "phone"
                        },
                        new
                        {
                            Id = new Guid("0d5c19d5-a289-402b-96a3-3135b6b03a52"),
                            Country = "USA",
                            Industry = "web",
                            Introduction = "Google Company",
                            Name = "Google",
                            Product = "search enging"
                        },
                        new
                        {
                            Id = new Guid("1475b207-6bf2-4c2e-86cd-a1cbbe9ec630"),
                            Country = "CN",
                            Industry = "web",
                            Introduction = "Dont be evil",
                            Name = "Alibaba",
                            Product = "electrophile"
                        });
                });

            modelBuilder.Entity("aspnetcore3_demo.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62491684-23c9-4ca7-b558-fe93ce663fc9"),
                            CompanyId = new Guid("1475b207-6bf2-4c2e-86cd-a1cbbe9ec630"),
                            DateOfBirth = new DateTime(1945, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "B001",
                            FirstName = "Qary",
                            Gender = 2,
                            LastName = "Uing"
                        },
                        new
                        {
                            Id = new Guid("82491684-23c9-4ca7-b558-fe93ce663f59"),
                            CompanyId = new Guid("0d5c19d5-a289-402b-96a3-3135b6b03a52"),
                            DateOfBirth = new DateTime(1945, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "f001",
                            FirstName = "yary",
                            Gender = 2,
                            LastName = "ssng"
                        },
                        new
                        {
                            Id = new Guid("bc801fd6-80e7-49d9-b239-0604fcc71b1e"),
                            CompanyId = new Guid("1475b207-6bf2-4c2e-86cd-a1cbbe9ec630"),
                            DateOfBirth = new DateTime(1937, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "B002",
                            FirstName = "Yichl",
                            Gender = 1,
                            LastName = "Ikng"
                        },
                        new
                        {
                            Id = new Guid("4f4ea5a8-5d05-41f1-bbcb-67cf14f09472"),
                            CompanyId = new Guid("7bfa2bc8-9748-4950-876e-9c733c4f5656"),
                            DateOfBirth = new DateTime(1985, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "C001",
                            FirstName = "Aary",
                            Gender = 2,
                            LastName = "Fing"
                        },
                        new
                        {
                            Id = new Guid("86fa9cf7-bfe2-46fa-b670-f3601641e689"),
                            CompanyId = new Guid("1475b207-6bf2-4c2e-86cd-a1cbbe9ec630"),
                            DateOfBirth = new DateTime(1995, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "C002",
                            FirstName = "Aichl",
                            Gender = 1,
                            LastName = "Fang"
                        },
                        new
                        {
                            Id = new Guid("b533a68e-8e64-46c2-afcf-b6b8b6c78982"),
                            CompanyId = new Guid("2aa4335e-bfa1-4820-94f9-f7bb717a4997"),
                            DateOfBirth = new DateTime(1985, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "A001",
                            FirstName = "Mary",
                            Gender = 2,
                            LastName = "King"
                        },
                        new
                        {
                            Id = new Guid("7aa8d6ec-8088-457b-a547-d68cdabb96a6"),
                            CompanyId = new Guid("2aa4335e-bfa1-4820-94f9-f7bb717a4997"),
                            DateOfBirth = new DateTime(1995, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "A002",
                            FirstName = "Michl",
                            Gender = 1,
                            LastName = "Wang"
                        });
                });

            modelBuilder.Entity("aspnetcore3_demo.Entities.Employee", b =>
                {
                    b.HasOne("aspnetcore3_demo.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
